description = "Generates a Git commit message based on staged changes."

prompt = """
Please generate a Conventional Commit message based on the following git diff:

```diff
!{git diff --staged}
```

After generating the message, create a commit with it.
"""
